name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Cambia a tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build de la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t dvtecno/authangular:latest .

      # 4. Push de la imagen a Docker Hub
      - name: Push Docker image
        run: |
          docker push dvtecno/authangular:latest

