name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Cambia 'main' al nombre de tu rama principal si es diferente
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login a Docker Hub (reemplaza con GitHub Container Registry si es necesario)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construir y etiquetar la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/authangular:latest .

      # 4. Publicar la imagen en Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/authangular:latest
